services:
  image-stichter:
    image: nginx:latest
    container_name: image-stichter
    restart: always
    ports:
      - "8081:80"
    volumes:
      - ./image-sticher/index.html:/usr/share/nginx/custom_html/image-stitcher.html:ro
      - ./image-sticher/nginx_site.conf:/etc/nginx/conf.d/default.conf:ro
